<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ITEM-AX31022" name="LoginTest - CH" tests="1" failures="0" timestamp="21 Aug 2017 14:57:18 GMT" time="0.028" errors="0">
  <testcase name="@BeforeMethod setUp" time="0.0" classname="com.dice.LoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.dice.base.BaseTest.setUp(BaseTest.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- @BeforeMethod setUp -->
  <testcase name="@AfterMethod tearDown" time="0.0" classname="com.dice.LoginTest">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="positiveLoginTest" time="0.002" classname="com.dice.LoginTest">
    <skipped/>
  </testcase> <!-- positiveLoginTest -->
</testsuite> <!-- LoginTest - CH -->
